baseURL = "https://johni12.github.io/snow_project/"
title = "Snow Project"
defaultContentLanguage = "de"
languageCode = "de"

[module]
  [[module.imports]]
    path = "github.com/gethinode/hinode"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch/v3"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"

[params.favicon]
  logo = "img/logo-dark.png"
  sizes = [16, 32, 96, 192]

[params.navigation]
  anchor = true
  logo = "/img/logo.png"
  logo-mode = true

[params.style]
  customCSS = ["scss/custom.css"]

[params.cards]
  summaryLength = 70   # <- hier legst du fest, wie viele Wörter im Card-Preview angezeigt werden

